### ISSUE TITLE
Instructions to boot from NVME SSD drive

### ISSUE THREAD

**Issue by Astrostecco** [devDucks/astroarch#102]
Ciao Mattia,

I tried the instructions referenced in the Github website, but it seems like there is a problem already with the 1st line of code: the system doesn't find the files to download (see attached image).

Any suggestion on how to proceed?

Thanks!
Stefano
![eeprom download issue](https://github.com/user-attachments/assets/ed0858dc-74f4-4c98-8793-a14e80028b6d)

**Comment by MattBlack85** [comment]
@Astrostecco that's a long issue with archlinux mirrors, try first to update the package database with `sudo pacman -Sy` and if fails again with 404, try few times, it should go

**Comment by Astrostecco** [comment]
it worked, thank you so much!! :)

**Comment by teoteo** [comment]
I had the same issue. I fixed editing the file /etc/pacman.d/mirrorlist:
`sudo nano /etc/pacman.d/mirrorlist`
replacing the line:
`Server = http://mirror.archlinuxarm.org/$arch/$repo`
with:
`Server = http://eu.mirror.archlinuxarm.org/$arch/$repo`
getting it from the [mirror list page](https://archlinuxarm.org/about/mirrors)

Should I get back to mirror.archlinuxarm.org in future?

**Comment by MattBlack85** [comment]
@teoteo probably not, ther main mirror which is supposed to load balance based on region still redirects to stuff that doesn't work
