### ISSUE TITLE
[SOLVED]cannot update fresh install 

### ISSUE THREAD

**Issue by albmef** [devDucks/astroarch#107]
hi
today i started from a fresh install.
i got an error while trying to update the whole distro

sudo pacman -Suy   
:: Synchronizing package databases...
 astromatto is up to date
 core is up to date
 extra is up to date
 community is up to date
 alarm is up to date
 aur is up to date
:: Starting full system upgrade...
...
Total Installed Size:  5212.06 MiB
Net Upgrade Size:       249.99 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 kstars-3.7.2-1-aarch64 is up to date
 astro_dmx-2.9.7-1-aarch64 is up to date
 indi-3rdparty-libs-2.0.9-1-aarch64 is up to date
 libindi-2.0.9-1-aarch64 is up to date
 indi-3rdparty-drivers-2.0.9-1-aarch64 is up to date
(553/553) checking keys in keyring                                                                                         [--------------------------------------------------------------------------] 100%
(553/553) checking package integrity                                                                                       [--------------------------------------------------------------------------] 100%
(553/553) loading package files                                                                                            [--------------------------------------------------------------------------] 100%
(553/553) checking for file conflicts                                                                                      [--------------------------------------------------------------------------] 100%
error: failed to commit transaction (conflicting files)
indi-3rdparty-libs: /usr/lib/libqhyccd.so.20 exists in filesystem
Errors occurred, no packages were upgraded.

seems that there is a problem with a very specific symbolic link:  /usr/lib/libqhyccd.so.20 is not owned by any package

» pacman -Qo /usr/lib/libqhyccd.so.24.4.1  
/usr/lib/libqhyccd.so.24.4.1 is owned by indi-3rdparty-libs 2.0.8-1
 

» pacman -Qo /usr/lib/libqhyccd.so.24     
/usr/lib/libqhyccd.so.24 is owned by indi-3rdparty-libs 2.0.8-1

» pacman -Qo /usr/lib/libqhyccd.so.20   
error: No package owns /usr/lib/libqhyccd.so.20.   <<<<<<<<<<<<<<<<<<ERROR<<<<<

» pacman -Qo /usr/lib/libqhyccd.so  
/usr/lib/libqhyccd.so is owned by indi-3rdparty-libs 2.0.8-1
                                 

so system upgrade cannot proceed 

» pacman -Qu | grep indi       
indi-3rdparty-drivers 2.0.8-1 -> 2.0.9-1
indi-3rdparty-libs 2.0.8-1 -> 2.0.9-1
libappindicator-gtk3 12.10.0.r298-3 -> 12.10.0.r298-4
libindi 2.0.8-2 -> 2.0.9-1

the faulty packages contains the file though

» pacman -Fl indi-3rdparty-libs | grep qhyccd   
warning: database file for 'community' does not exist (use '-Fy' to download)
indi-3rdparty-libs usr/include/libqhy/qhyccd.h
indi-3rdparty-libs usr/include/libqhy/qhyccdcamdef.h
indi-3rdparty-libs usr/include/libqhy/qhyccderr.h
indi-3rdparty-libs usr/include/libqhy/qhyccdstruct.h
indi-3rdparty-libs usr/lib/libqhyccd.so
indi-3rdparty-libs usr/lib/libqhyccd.so.20    <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
indi-3rdparty-libs usr/lib/libqhyccd.so.24.7.29
indi-3rdparty-libs usr/lib/udev/rules.d/85-qhyccd.rules

regards,
bob

**Comment by MattBlack85** [comment]
@albmef I vaguely remember this issue, can you try update-astroarch instead of pacman?

**Comment by albmef** [comment]
hi 
you're right i had to to an update-astroarch instead
thanks for your support
bob
