### ISSUE TITLE
Duplicated char in terminal

### ISSUE THREAD

**Issue by MattBlack85** [devDucks/astroarch#11]
Sometimes zsh calculates a bad offset to display chars, this is probably due the fact LC_CTYPE is never set during the image preparation.
Adding it to .zshrc won't be enough to fix the issue, `locale-gen` should be invoked at bootstrap time to fix it (so en_US.UTF-8 should be uncommented before running locale-gen)

**Comment by ManasviGoyal** [comment]
I would like to work on this. Can you please elaborate? Do I need to add - `export LC_CTYPE=en_US.UTF-8` ?

**Comment by MattBlack85** [comment]
hi @ManasviGoyal, yes that should in theory fix the issue, a confirmation of the fix is welcome as well

**Comment by MattBlack85** [comment]
fixed in 65fd9aec4f62767cf0b22f9b32d82cdedd78980a
