### ISSUE TITLE
Fresh v1.9 image, update-astroarch failure on conflicting files

### ISSUE THREAD

**Issue by 0ctane** [devDucks/astroarch#116]
raspberry pi 4 with astroarch 1.9
After initial boot, connected to local wifi and ran 'update-astroarch'. Update failed with:

> error: failed to commit transaction (conflicting files)
> /usr/share/xdg-desktop-portal/kde-portals.conf exists in both 'xdg-desktop-portal-kde' and 'plasma-workspace'
> Errors occurred, no packages were upgraded.

..

**Comment by MattBlack85** [comment]
hi @0ctane this is fixed in upstream now, update with `update-astroarch` again and it should work, feel free to re-open should it be still broken
