### ISSUE TITLE
Fail updating astroarch.

### ISSUE THREAD

**Issue by jmvillalba** [devDucks/astroarch#12]
When I try to update astroarch using sudo pacman -Syu. I get a error with astroarch.db download.
`failed retrieving file astroarch.db from astroarch.astromatto.com:9000: the request url returned error: 404`

**Comment by MattBlack85** [comment]
hi @jmvillalba my server died when I was on holiday, I will rebuild it today, so it should be available again in a couple of hours

**Comment by MattBlack85** [comment]
@jmvillalba everything should be up since last week. I am closing this but please feel free to re-open if something is still now working, thanks!

**Comment by jmvillalba** [comment]
Thanks for your work.

Great!
