### ISSUE TITLE
default password for user astronaut?

### ISSUE THREAD

**Issue by wbirk** [devDucks/astroarch#23]
... but what is the root password by default? whatever i do, i get a request: password for astronaut: and neither astro, astronomy or root works ...

**Comment by wbirk** [comment]
i tried it hard but no :D ... making a new sd image again, maybes something got messed up ....

**Comment by MattBlack85** [comment]
also, if it fails again I would suggest to try to ssh using the same combination of user/pass

rebooting sometimes also helps to solve this issue

**Comment by wbirk** [comment]
it works after redoing the image. i only learned from the sudo pwd from the indiforum, btw, it is not mentioned in the git. maybe that messed up something ...
thanks anyhow - great work!

**Comment by MattBlack85** [comment]
@wbirk you are absolutely right, for some reasons I was convinced I put somewhere in the readme the password but there is 0 trace of it, I will add it soon (and possibly, since this is something I have on my mind since a while, making astronaut able to use sudo without password)

Thanks!

**Comment by wbirk** [comment]
i have to thank you :)
