### ISSUE TITLE
Kstars not starting in Manjaro

### ISSUE THREAD

**Issue by LionBit76** [devDucks/astroarch#29]
On my Manjaro Laptop kstars is not starting.

`kstars: error while loading shared libraries: libwcs.so.7: cannot open shared object file: No such file or directory`

A few days ago there was a big update for Manjaro, since then Kastars doesn't start anymore.
I entered the repository, it was still working fine a few weeks ago.
wcslib is now at version 8.1-1

**Comment by LionBit76** [comment]
Hi @MattBlack85 
Thanks for the quick reply :)
My cache is already empty, so a downgrade is no longer possible. It doesn't matter, I still have a Kubuntu laptop, everything works there too. I'll wait until the problem is resolved and then I'll switch to Astroarch.

**Comment by MattBlack85** [comment]
cool, will ping you here after the release the, thanks again!

**Comment by MattBlack85** [comment]
hi @LionBit76 I just compiled and released indi 2.0.3 and kstars 3.6.6, I recompiled stellarsolver (which was the real issue) against wcslib8), feel free to try and erport back if there is still any issue

**Comment by LionBit76** [comment]
Thanks @MattBlack85 for the updates, it seems to be working again :) 
Thumbs up!

**Comment by MattBlack85** [comment]
@LionBit76 cool! May I ask you just one more thing? How did you get to know about astroarch? :) I am just curious to know which sources are working

**Comment by LionBit76** [comment]
Of course, first on [https://forum.astronomie.de](url) and later again on [https://indilib.org](url)
I run a small astro blog, so I'll report about it sometime. [https://astrophoto.lionbit.com](url)
But before that I have to switch my "INDIbox" to AstroArch and test it :)
I think, Arch Linux is a much better base than Ubuntu and i really hope that this project will become a big community.
CS
Lucas

**Comment by MattBlack85** [comment]
> Of course, first on [https://forum.astronomie.de](url) and later again on [https://indilib.org](url) I run a small astro blog, so I'll report about it sometime. [https://astrophoto.lionbit.com](url) But before that I have to switch my "INDIbox" to AstroArch and test it :) I think, Arch Linux is a much better base than Ubuntu and i really hope that this project will become a big community. CS Lucas

thank you very much! Hope to have you onboarded soon!
