### ISSUE TITLE
Passwords don't work

### ISSUE THREAD

**Issue by vidrazor** [devDucks/astroarch#31]
I just installed AstroArch on an 8 gig Pi4, and when I try to run the updates or change location and time, it won't recognize the passwords. I've tried astro, astronaut, astroarch, AstrArch, nothing works.

So, what' sup?

Thanks.

**Comment by vidrazor** [comment]
...also, I connected to the computer through a local network using VNC, and it never asked for a password, it just logged right in.

**Comment by MattBlack85** [comment]
@vidrazor for the passwords not working, try to reboot, I got a couple of reports on that and rebooting usually solves it. Fr the VNC, there is no password to connect to it, that's by design, I believe you were expecting the password like astroberry does, but there is none on AstroArch
