### ISSUE TITLE
Two useful packages

### ISSUE THREAD

**Issue by sc74** [devDucks/astroarch#49]
Will it be possible to get 2 AUR packages that I really like as an Arch user? 

The first is downgrade to downgrade certain packages when troubleshooting your system. Quite useful to experienced users

The second is arch-update. A great script that doesn't just do normal +Aur +Flatpak updates. It informs about the latest news from Arch Linux, allows you to remove orphaned packages and old packages from the cache. It processes pacnew/pacsave files. And also offers a restart if there has been a kernel update.

For more information: https://github.com/Antiz96/arch-update

Thanks in advance.

Stéphane

**Comment by MattBlack85** [comment]
those 2 packages are now available on the astromatto repo to be installed. Feel free to add a documentation section on the README @sc74
