### ISSUE TITLE
FTP server?

### ISSUE THREAD

**Issue by sc74** [devDucks/astroarch#53]
Maybe it would be useful to have a ftp server such as vsftpd on ArstroArch? What do you think ?

**Comment by sc74** [comment]
If you decide to include FTP here is a suggested code once the package is installed.

sed -i 's/#write_enable=YES/write_enable=YES/g' /etc/vsftpd.conf
sed -i 's/#local_enable=YES/local_enable=YES/g' /etc/vsftpd.conf
sed -i 's/#ascii_upload_enable=YES/ascii_upload_enable=YES/g' /etc/vsftpd.conf
sed -i 's/#ascii_download_enable=YES/ascii_download_enable=YES/g' /etc/vsftpd.conf
sed -i 's/#chroot_local_user=YES/chroot_local_user=YES/g' /etc/vsftpd.conf
sed -i 's/#chroot_list_enable=YES/chroot_list_enable=YES/g' /etc/vsftpd.conf
sed -i 's/#chroot_list_file=/etc/vsftpd.chroot_list/chroot_list_file=/etc/vsftpd.chroot_list/g' /etc/vsftpd.conf
sed -i 's/#ls_recurse_enable=YES/ls_recurse_enable=YES/g' /etc/vsftpd.conf
cat > /etc/vsftpd.conf << 'EOL'
# if not specified, users' home directory equals FTP home directory
local_root=public_html
# turn off seccomp filter if cannot login normally
seccomp_sandbox=NO
EOL
touch /etc/vsftpd.chroot_list
cat > /etc/vsftpd.chroot_list << 'EOL'
# add users you allow to move over their home directory
astronaut
EOL

Good day.


Stephane

**Comment by MattBlack85** [comment]
hi @sc74 

I think an FTP server may be of interest for some people, but definitely I think is more of an edge case.
For these kind of things, I think the best solution is to provide clear documentation on how to achieve it in case you need it.

AstroArch grew quite a lot in the number of packages that are present by default and extra care should be taken to avoid adding more (together with dependencies) that are rarely used.

I will mark these kind of issues with the `add documentation` label

**Comment by sc74** [comment]
I understand. This is a suggestion, because I saw that Jasem had implemented it in Stellarmate and that he suggested that some people use it when transferring large files such as astrometry files. 

My proposal is still taken from the Arch wiki https://wiki.archlinux.org/title/Very_Secure_FTP_Daemon

**Comment by MattBlack85** [comment]
this will be a zsh plugin

**Comment by MattBlack85** [comment]
fixed in 1.9
