### ISSUE TITLE
AstroArch Hotspot refuses connection. Password Wrong?

### ISSUE THREAD

**Issue by profhuster** [devDucks/astroarch#56]
Raspberry Pi 3 B
astroarch-1.7.0.img.gz
On first boot the hotspot AstroArch shows up, but won't connect with password astronaut or astro.
Fortunately I could connect with Ethernet cable.

**Comment by sc74** [comment]
On the Github page, there is the password section.

It says: “the password for the AstroArch WiFi hotspot is astronomy”

**Comment by profhuster** [comment]
Sorry for my typo. "astronomy" does not work either.
