### ISSUE TITLE
Resize primary partition

### ISSUE THREAD

**Issue by sc74** [devDucks/astroarch#57]
A suggestion for resizing the / partition.

A /bin/bash script resize_disk.sh

nano resize_disk.sh
#!/bin/bash
export ROOT_DISK=$(blkid --match-token PARTUUID=cafd14b5-02 -o device)
echo ${ROOT_DISK}
if [ ${ROOT_DISK} = "/dev/mmcblk0p2" ]; then
export GROW_DISK=$(blkid --match-token PARTUUID=cafd14b5-02 -o device | sed 's/.\{2\}$//')
else
export GROW_DISK=$(blkid --match-token PARTUUID=cafd14b5-02 -o device | sed 's/.\{1\}$//')
fi
growpart ${GROW_DISK} 2
resize2fs -p ${ROOT_DISK}

Make the file executable
chmod +x resize_disk

The systemd service resize_once.service to launch the script

nano resize_once.service
[Unit]
Description=Extend root partition and resize ext4 file system
After=local-fs.target
Wants=local-fs.target

[Service]
ExecStart=/home/astronaut/.astroarch/systemd/resize_disk
Type=oneshot

[Install]
WantedBy=multi-user.target

Then systemctl enable resize_once.service

Good day.

Stephane

**Comment by MattBlack85** [comment]
solved in https://github.com/devDucks/astroarch/commit/8187fbfc0a80941511daa4c7c5da6b44614345b4

there is no hardcoded partitions, should work on every media
