### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by sc74** [devDucks/astroarch#60]
A suggestion for installing and enable Bluetooth.

Install
sudo pacman -S bluez bluez-utils bluez-hid2hci bluedevil

Uncomment in /etc/bluetooth/main.conf
DiscoverableTimeout = 0
AlwaysPairable = true
PairableTimeout = 0
AutoEnable=true

Start the service
sudo systemctl start bluetooth

With this, I was able to connect my Bluetooth keyboard and mouse without any issues.

Good day

Stéphane

**Comment by MattBlack85** [comment]
Is there a widget on the tray for the Bluetooth with just bluez?

**Comment by sc74** [comment]
It's the bluedevil package that implements this in KDE

It is noted in the wiki https://wiki.archlinux.org/title/bluetooth

"Bluedevil — KDE's Bluetooth tool. If there is no Bluetooth icon visible in Dolphin and in the system tray, enable it in the system tray options or add a widget. You can configure Bluedevil and detect Bluetooth devices by clicking the icon. An interface is also available from the KDE System Settings"

![Screenshot_20240303_143315](https://github.com/devDucks/astroarch/assets/7612483/62b8757d-1b84-4cd2-a55a-977640613306)

**Comment by MattBlack85** [comment]
done in c7d65e048c25f8708b6f74801b194965a8273dea
