### ISSUE TITLE
For new users and local language setting

### ISSUE THREAD

**Issue by sc74** [devDucks/astroarch#62]
For the next version, would it be possible to run a script on first startup to request the language and geographic area for the time?

Indeed, new or basic ArchLinux users whose language is not English, it can be very complicated to correctly set the language for the vconsole, X11.

Going back to what Manjaro does, a suggestion would be to use the dialog package and a script.

An example that should of course be improved

  #! /bin/bash

  #clearing variables

  TIMEZONE=""
  LOCALE=""
  X11KEYMAP=""

  #Using Dialog to ask for user input for variables

      let i=0
	W=()
	while read -r line; do
		let i=$i+1
		W+=($line "")
	done < <( timedatectl list-timezones )
	TIMEZONE=$(dialog --clear --title "Manjaro ARM Installer" \
	--menu "Choose your timezone!" 20 50 15 \
	"${W[@]}" 3>&1 1>&2 2>&3 3>&- \
	)

	let i=0
	W=()
	while read -r line; do
		let i=$i+1
		W+=($line "")
	done < <( cat /etc/locale.gen | grep "UTF-8" | tail -n +2 | sed -e 's/^#*//' | awk '{print $1}' )
	LOCALE=$(dialog --clear --title "AstroArch Installer" \
		--menu "Choose your locale!" 20 50 15 \
		"${W[@]}" 3>&1 1>&2 2>&3 3>&- \
		)

	let i=0
	W=()
	while read -r line; do
		let i=$i+1
		W+=($line "")
	done < <( localectl list-keymaps )
	CLIKEYMAP=$(dialog --clear --title "AstroArch Installer" \
		--menu "Choose your TTY keyboard layout:" 20 50 15 \
		"${W[@]}" 3>&1 1>&2 2>&3 3>&- \
	)

       let i=0
	W=()
	while read -r line; do
		let i=$i+1
		W+=($line "")
	done < <( localectl list-x11-keymap-layouts )
	X11KEYMAP=$(dialog --clear --title "AstroArch Installer" \
		--menu "Choose your X11 keyboard layout:" 20 50 15 \
		"${W[@]}" 3>&1 1>&2 2>&3 3>&- \
	)

    #system setup

    ln -sf /usr/share/zoneinfo/"$TIMEZONE" /etc/localtime
    sed -i s/"#$LOCALE"/"$LOCALE"/g /etc/locale.gen
    echo "LANG=$LOCALE" | tee --append $TMPDIR/root/etc/locale.conf
    locale-gen
    echo "KEYMAP=$CLIKEYMAP" | tee --append $TMPDIR/root/etc/vconsole.conf
    echo 'Section "InputClass"' > $TMPDIR/root/etc/X11/xorg.conf.d/00-keyboard.conf
    echo 'Identifier "system-keyboard"' >> $TMPDIR/root/etc/X11/xorg.conf.d/00-keyboard.conf
    echo 'Option "XkbLayout" "us"' >> $TMPDIR/root/etc/X11/xorg.conf.d/00-keyboard.conf
    echo 'EndSection' >> $TMPDIR/root/etc/X11/xorg.conf.d/00-keyboard.conf
    sed -i s/"us"/"$X11KEYMAP"/ $TMPDIR/root/etc/X11/xorg.conf.d/00-keyboard.conf
    unset LANG
    source /etc/profile.d/locale.sh

**Comment by MattBlack85** [comment]
superseded by #75
