### ISSUE TITLE
Promoted the Astro Monitor software

### ISSUE THREAD

**Issue by sc74** [devDucks/astroarch#64]
Hi,

It is a shame that the AstroArch GitHub page does not highlight the Astro Monitor software more.

Indeed, knowing that there is a simple method to save kstars/indi data would encourage users to switch to AstroArch. However, nothing explicitly indicates that this can be done.

Although it is true that a link exists to discover Astro Monitor, it does not clearly indicate the benefits of the software. 

In addition, the GitHub page explaining the use of Astro Monitor is much too complicated for a user who has no idea what a token, a bot, or telegram for certain is.

It would be nice if there was an insert with a simple explanation to retrieve the token on Telegram, install Astro Monitor on your OS, back up the data and recover it once the AstroArch image is installed.

**Comment by MattBlack85** [comment]
completed
