### ISSUE TITLE
Unresponsive on Raspberry Pi 3?

### ISSUE THREAD

**Issue by Driffster** [devDucks/astroarch#66]
Hello, I tried my luck and installed Astroarch on raspberry pi 3.

I am getting the system running, but as soon as I get the GUI, I am unable to do anything, everything takes in the order of minutes to responds ( for example it takes 5 minutes (or more) to draw the system setting windows (without any content inside..). 

Any people had better luck? I was thinking it might be a SD card issue, but I was able to run Astroberry fairly well on the same sd card.

Cheers

**Comment by MattBlack85** [comment]
hi @Driffster how are you connected to the pi?

**Comment by Driffster** [comment]
Directly plugged to the hdmi monitor and with keyboard and mouse.

**Comment by MattBlack85** [comment]
@Driffster while the raspi 3 is old(ish) hardware I am not sure if this is a hardware problem (specifically, related to HDMI and resolution), I was making some tests on my end but I broke my mini hdmi adapter and I need to order a new one, can you do the following tests in the meanwhile and report back so we can narrow down the problem? (video are also well welcomed)

- can you connect to the hotspot and try VNC to see how it compares (HDMI must be disconnected)?
- can you connect to the hotspot and try VNC to see how it compares (HDMI must be connected)?
- can you plumb it to your router via eth cable and compare?
- can you try to run `xrandr -s 1280x720` in the terminal and see how it compares?

**Comment by Driffster** [comment]
There seems to be something wrong with my install. Headless with no device pluged in: I am able to connect to the hotspot, but I am not able to open the vnc.
The best I got to is the loading screening:
![image](https://github.com/devDucks/astroarch/assets/15223968/7b7e34d8-c18c-41e9-86da-ae7a312a29cd)

I can't run any commands.. system hangs on anything I touch, can't reach the terminal.

**Comment by MattBlack85** [comment]
10.42.0.1 instead of astroarch.local leads to the same?

**Comment by Driffster** [comment]
I reflashed another SD card (which I have a bit more confidence on..) (btw it is astroarch-1.8.0.img). This time I didn't plug it at all to HDMI and ran it for the first time headless. Now I can connect by VNC via wifi, I got a screen, but it is still totally unresponsive once there: this is the screen after a few minutes logged in:
![image](https://github.com/devDucks/astroarch/assets/15223968/369fb64c-ce1f-4a47-b696-e1f942dad930)
 Maybe its doing to much memory swapping on the sd card I don't know. I will try a lightweight archlinux distro on it and see.

**Comment by sc74** [comment]
Hi Driffster,

Are you using your browser to log in to AstroArch?

Don't have vnc software on your pi 3?

**Comment by Driffster** [comment]
sc74: Logging from the PC to the Pi3, using Astroarch so its the vnc of the Pi3. 

If someone actually was able to run the latest Astroarch on a Pi3 and got it to work somehow I am interested to know. 
But for me either my Pi3 is defective or Astroarch is too heavy for the Pi3.

**Comment by sc74** [comment]
It is likely that AstroArch is too heavy for a pi 3 1G

On the other hand, we don't know what it means for vnc. Do you use a vnc client on your pi or do you go to the browser by typing http://astroarch.local:8080/vnc.html

**Comment by Driffster** [comment]
No I used the web page. That was working for the first few minutes the raspberry pi is on.

**Comment by sc74** [comment]
Try installing a vnc client on your pc and connecting with it. It's probably better than the web page

**Comment by Driffster** [comment]
You don't understand: the raspberry itself is unresponsive as soon as the desktop starts. Right now I reach a state where I have a black screen with a cursor in it, nothing else. The whole system degrades after a few boots. I tried it on 3 diferent SD cards.

Anyways if it doesn't work on any RP3 might be worth to update the site and specify its just for RP4 and 5.

**Comment by MattBlack85** [comment]
Yes, I think it's too much too handle for a pi3, will modify the readme with supported models. Thank you!

**Comment by MattBlack85** [comment]
Closing as the doc has been updated
