### ISSUE TITLE
First installation 1.8 and update-astroarch command

### ISSUE THREAD

**Issue by sc74** [devDucks/astroarch#69]
Good morning,

I just did a fresh install of AstroArch 1.8 and connected with vnc. After updating with update-astroarch in a console, I clicked the restart button. 

![Copie d'écran_20240312_185106](https://github.com/devDucks/astroarch/assets/7612483/59cf85d0-cf41-401f-b896-5af458620382)

This did not restart the pi, but only logged out to display this

![Copie d'écran_20240312_171741](https://github.com/devDucks/astroarch/assets/7612483/c58dec90-7afa-46a0-8bb1-bb767a4103da)

It seems that it is necessary to do a reboot command after update-astroarch in the console in order to restart the pi correctly.

Maybe it would be nice to have a note in the first boot part indicating what to do if you end up on the sddm login page.

Have a good day and clear skies.

**Comment by MattBlack85** [comment]
as the most recent image has already KDE6 installed, I consider this as solved
