### ISSUE TITLE
dopo aggiornamento non si accede

### ISSUE THREAD

**Issue by AstroVersilia** [devDucks/astroarch#70]
Ciao Mattia

ho aggiornato e questo è il risultato

![image](https://github.com/devDucks/astroarch/assets/153842517/050f7d69-52ac-49c9-a00f-81be5178ae50)

l'accesso lo faccio via novnc ma quando entro si resetta e risiamo da capo.

Cosa posso fare?

Ciao e grazie

Paolo

**Comment by MattBlack85** [comment]
ciao Paolo hai aggiornato con `pacman` o con `update-astroarch`? La versione che montavi era beta o quella del link che c'è ora?

**Comment by AstroVersilia** [comment]
Ciao Mattia

Ho aggiornato mediante l'icona in basso a destra che segnala gli
aggiornamenti.
La versione è quella che ho scaricato qualche giorno fa (1.8), avevo
aggiornato e andava benissimo, adesso invece dopo 500 mb di download
presenta questo problema.
C'è modo di uscirne senza dover reinstallare il sistema?

Grazie,

Paolo

Il ven 15 mar 2024, 16:33 Mattia Procopio ***@***.***> ha
scritto:

**Comment by MattBlack85** [comment]
@AstroVersilia dai `update-astroarch` e fai un hard reboot. Dovrebbe sistemarsi

C'è un fix di una configurazione ma viene sistemato solo con `update-astroarch`

**Comment by MattBlack85** [comment]
@AstroVersilia scusa, non sono stato preciso al 100%. Intendevo dando il comando accedendo con ssh, riesci ad accedere tramite ssh?

**Comment by AstroVersilia** [comment]
Purtroppo non sono così smanettone, saresti così gentile da indicarmi la
procedura?
Grazie mille

Il ven 15 mar 2024, 17:52 Mattia Procopio ***@***.***> ha
scritto:

**Comment by MattBlack85** [comment]
@AstroVersilia no problem, forse allora facciamo prima così:

quando ti si presenta la schermata c'è una scritta `Desktop session: plasma wayland` dovresti poter scegliere x11 lì, dopo che cambi la session in x11 metti la password per astronaut e ti parte come al solito.

Appena dentro apri il terminale e lancia `update-astroarch` e fai un hard reboot del pi. Dovrebbe sistemarsi automaticamente dopo

**Comment by AstroVersilia** [comment]
Proviamo, ti tengo aggiornato

Grazie mille per ora

Il ven 15 mar 2024, 17:58 Mattia Procopio ***@***.***> ha
scritto:

**Comment by AstroVersilia** [comment]
Ripartito e tutto a posto.

Grazie per i sempre preziosi aiuti

A presto

Paolo

Il ven 15 mar 2024, 18:06 Paolo Dori ***@***.***> ha scritto:

**Comment by MattBlack85** [comment]
Non c'è di che
