### ISSUE TITLE
Driver Indi per Focheggiatore

### ISSUE THREAD

**Issue by zurigo66** [devDucks/astroarch#79]
Salve a tutti.
Ho da poco acquistato su Aliexpress questo focheggiatore elettrico molto simile (a parte il colore) al modello EAf della ZWO. Viene definito come GEMINI Electric focuser pro. Sul sito viene dichiarato che è compatibile con driver Ascom e Indi quindi gestibile sia con Nina sia con Ekos.  Possiedo sia Astroberry che Astroarch col quale mi trovo MOLTO bene ma di questo dispositivo non ho trovato il driver corrispondente, nemmeno tra gli other, può essere che non sia stato ancora rilasciato il driver Indi? 
Mi potete aiutare? 
Grazie in anticipo!!
Michele

**Comment by teoteo** [comment]
Ciao, può essere che abbiano usato un driver già presentente. Hai già provato a sceglierne altri? 
Proverei ZWO EAF, MoonLite e quelli presenti in DIY. Puoi anche chiedere al produttore qual è il driver adatto.

**Comment by MattBlack85** [comment]
@zurigo66 concordo con @teoteo 

ho cercato il codice INDI ma non c'è un solo riferimento a "gemini" quindi le opzioni sono due, una bella e una brutta :D

Opzione 1 (la bella) - usa un driver di altre case (o magari uno libero come appunto il moonlight) ma non c'è nessun riferimento a esso sulla pagina quindi bisogna per forza chiedere al venditore
Opzione 2 (la brutta) - hanno scritto fesserie sull'offerta e INDI non è supportato

**Comment by MattBlack85** [comment]
non sono sicuro del significato, ma il venditore dice che il driver è
```
Indi in diy-myfocuser
```

ce ne sono 4 da quello che vedo, ci sarebbe da provarli

**Comment by teoteo** [comment]
> non sono sicuro del significato, ma il venditore dice che il driver è
> 
> ```
> Indi in diy-myfocuser
> ```
> 
> ce ne sono 4 da quello che vedo, ci sarebbe da provarli

È probabile che sia il [MyFocuserPro2](https://sourceforge.net/projects/arduinoascomfocuserpro2diy/) di Robert Brown.
@zurigo66 Se si connette, dovresti vedere qualcosa del genere:
<img width="1680" alt="Screenshot 2024-03-21 alle 23 16 42" src="https://github.com/devDucks/astroarch/assets/789650/6df3eee2-cda0-4d0c-8b72-167e751a3867">

**Comment by zurigo66** [comment]
Allora ragazzi vi comunico con gioia che effettivamente come suggerito da teoteo si tratta proprio del driver MyFocuserPro2.  
Collegato immediatamente e funziona perfettamente :-) :-) :-)
Spero che possa essere utile ad altri utenti della comunity.
Grazie a tutti!!
P.S.  Mattia continua così sei un grande!!

**Comment by MattBlack85** [comment]
grazie, qua chiudo allora se è tutto a posto!

**Comment by zurigo66** [comment]
Tutto a posto di nuovo grazie :-)
