### ISSUE TITLE
Keine Verbindung zur FRITZ!Box 

### ISSUE THREAD

**Issue by Eddy1972N** [devDucks/astroarch#93]
Seit dem letzten Update kann ich keine w-lan Verbindung zur Fritz Box herstellen! Mit der vorherigen Version funktioniert das sehr gut was ist bei euch passiert?? 

Bitte bug Fixing ![image](https://github.com/user-attachments/assets/98347ec0-b9d5-4a11-a6f4-7c87583f6d94)

**Comment by Eddy1972N** [comment]
No conect on wlan0 bevor the Update nativ v1.9 is conect the wlan 0 on raspberry pi4 !!! Please kill the bug ! I'm Not amused about that ! Please bugfix!!

**Comment by MattBlack85** [comment]
@Eddy1972N I may have a look but the screenshot you sent is a bit unclear. It seems you made a lot of netowors and you seem to run a WiFi adapter in addition to the raspberry WiFi, is this correct?

**Comment by Eddy1972N** [comment]
Des i made an Access Point 3of them! But i Cant the Main w-lan From RPI 4 (wlan0 ) Not conect on the router at Home ! On the nativ 1.9 was it Connect ! 

Pleasanton try it make 3 Access Point on the Software! On the 1.9 and than past of the Update From the Server! Any Protokoll is broken ! I think so!

**Comment by MattBlack85** [comment]
@Eddy1972N not sure I understand you, are you saying it was working and then you updated the system and it doesn't work anymore?

**Comment by Eddy1972N** [comment]
> @Eddy1972N not sure I understand you, are you saying it was working and then you updated the system and it doesn't work anymore?

That right!

**Comment by Eddy1972N** [comment]
Thats all i put my Passwort in it but nothing! Its Kick me out



![image](https://github.com/user-attachments/assets/2c960dec-6def-45f6-a59c-ae07e13669b8)

**Comment by mistertroy** [comment]
I've had the same problem. I did an update prior to imaging on Friday night, lost wifi, could only connect to the hotspot, so did it that way friday night. Sat down and tried to sort it out on saturday but couldn't, so reflashed the card. It was able to connect to wifi, so i did another update - then it couldn't. Was having issues with Kstars crashing when ending Ekos anyway, so probably needed a reflash anyway! Am able to look into it again today, so am currently reflashing the SD card.

I'm using a Pi4, running AA1.9. No problems before, kept it mostly bleeding edge. won't be doing that anymore!

**Comment by mistertroy** [comment]
And after reflashing it all works. I'm not going to update though until it gets cloudy again and I've backed everything up!

**Comment by MattBlack85** [comment]
I will look for any NetowrkManager updates lately, I am not sure at the moment if was any of its updates or simply a kernel that broke it

**Comment by Eddy1972N** [comment]
And where is the Bug ???

**Comment by MattBlack85** [comment]
I have no idea, that is not something I wrote,  use or mantain. That is a package released from KDE and distributed by the ArchLinuxARM team

**Comment by Eddy1972N** [comment]
> I will look for any NetowrkManager updates lately, I am not sure at the moment if was any of its updates or simply a kernel that broke it

Ist nothing change With the last Update at 02.08.24 !!!!

Please Bug fix

**Comment by sc74** [comment]
Hi. It seems that the pis are affected by a problem for the brcmfmac driver. View your logs with dmesg -w. If you have something like this

brcmfmac: brcmf_set_channel: set chanspec 0xd0...fail, reason -52

So, try to apply the solution found for this issue

https://github.com/home-assistant/operating-system/issues/3367#issuecomment-2269028464

create a file /etc/modprobe.d/brcmfmac.conf containing this line:

options brcmfmac feature_disable=0x82000

and reboot.

Another thing, if you are using openssh please read the archlinux page 

https://archlinux.org/news/the-sshd-service-needs-to-be-restarted-after-upgrading-to-openssh-98p1/

**Comment by MattBlack85** [comment]
closed as fixed in 1.9.2
